FROM fedora:latest
### DOPR START, code until tag `CDIC END` was auto-generated by cdic service

RUN yum install -y dnf dnf-plugins-core \
    && mkdir -p /etc/yum.repos.d/
RUN dnf copr enable -y msuchy/copr && \
    dnf copr enable -y msuchy/scl-utils
### DOPR END

